### ISSUE TITLE
Ipadapter error

### ISSUE THREAD

**Issue by Beamhi** [kijai/ComfyUI-BrushNet-Wrapper#1]
I get this error while trying to use the ipadapter node:
Traceback (most recent call last):
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\nodes.py", line 394, in loadmodel
    ip_adapter = IPAdapter(brushnet['pipe'], ipadapter_path, image_encoder, device=device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\ip_adapter\ip_adapter.py", line 34, in __init__
    ipadapter_model = torch.load(ipadapter_ckpt_path, map_location="cpu")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nux\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\xc8'.

**Comment by kijai** [comment]
Which model are you trying to use with it? I only tested with the original .bin models: `ip-adapter-plus_sd15.bin` and
 `ip-adapter_sd15.bin`

**Comment by Beamhi** [comment]
Thanks! it works now, I had safetensors and it wasn't working so I had to download .bin

**Comment by kijai** [comment]
> Thanks! it works now, I had safetensors and it wasn't working so I had to download .bin

I added support for loading it from .safetensors now as well.
