### ISSUE TITLE
about pipeline error.Pls help,txs

### ISSUE THREAD

**Issue by laogu1027** [kijai/ComfyUI-BrushNet-Wrapper#27]
Traceback (most recent call last):
  File "E:\ai\ComfyUI\nodes.py", line 1876, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ai\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ai\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\nodes.py", line 29, in <module>
    from .brushnet.pipeline_brushnet import StableDiffusionBrushNetPipeline
  File "E:\ai\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\brushnet\pipeline_brushnet.py", line 26, in <module>
    from diffusers.pipelines.pipeline_utils import DiffusionPipeline, StableDiffusionMixin
ImportError: cannot import name 'StableDiffusionMixin' from 'diffusers.pipelines.pipeline_utils' (E:\ai\ComfyUI\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py)

**Comment by kijai** [comment]
Need to update diffusers.
