### ISSUE TITLE
 Brushnet Model Loader does is not working

### ISSUE THREAD

**Issue by KorDum** [kijai/ComfyUI-BrushNet-Wrapper#3]
Hello! I'm getting an error on the brushnet model loader node.

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet-Wrapper\nodes.py", line 138, in loadmodel
    set_module_tensor_to_device(new_unet, key, device=device, dtype=dtype, value=converted_unet[key])
  File "F:\StableDiffusion\ComfyUI\.venv\lib\site-packages\accelerate\utils\modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([640, 640]) in "weight" (which has shape torch.Size([640, 640, 1, 1])), this look incorrect.
```

What other information do I need to provide?

**Comment by kijai** [comment]
Which model are you trying to load for it? This only works with 1.5 models as they have not released SDXL version.

**Comment by KorDum** [comment]
Yes, I did try it for SDXL. Thanks, I'll wait for support.
